[versions]
activityCompose = "1.10.0"
agp = "8.8.0"
coilBom = "3.0.4"
composeBom = "2025.01.00"
coreKtx = "1.15.0"
dependencyVersions = "0.51.0"
desugarJdk = "2.1.4"
espressoCore = "3.6.1"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.1.0"
lifecycleRuntimeKtx = "2.8.7"
ktor = "3.0.3"
materialIconsExtended = "1.7.6"
slf4j = "1.7.36"
coroutines = "1.10.1"
datetime = "0.6.1"
serialization = "1.8.0"
ksp = "2.1.0-1.0.29"
hilt = "2.55"

[libraries]
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coilBom" }
desugarjdklibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdk" }
coil-bom = { module = "io.coil-kt.coil3:coil-bom", version.ref = "coilBom" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp" }
coil-test = { module = "io.coil-kt.coil3:coil-test" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-plugin-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-plugin-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-plugin-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-plugin-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-plugin-logging-backend = { module = "org.slf4j:slf4j-android", version.ref = "slf4j" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
dependency-version = { id = "com.github.ben-manes.versions", version.ref = "dependencyVersions" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[bundles]
ktor-client = ["ktor-client-core", "ktor-client-okhttp", "ktor-plugin-auth", "ktor-plugin-content-negotiation", "ktor-plugin-logging", "ktor-plugin-logging-backend", "ktor-plugin-serialization-json"]